#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 Guy Shtainer
"""Build a double-clickable rec2mp4.app for macOS.

    python tools/make_macos_app.py                 # -> dist/rec2mp4.app
    python tools/make_macos_app.py --to ~/Applications
    python tools/make_macos_app.py --python /path/to/python

What this is: a **launcher bundle**, not a frozen distributable. It is a real
.app — its own Dock icon, no Terminal window, double-click to run — but it
starts the rec2mp4 already in this working copy, using an interpreter that has
the stack (Pillow + the vendored mGBA bindings + ffmpeg on PATH). That is the
honest thing to build today, because a self-contained app would also have to
ship those vendored native bindings and an ffmpeg binary; see README
"Desktop icon" for what a true standalone build would need.

Both paths are baked in at build time and can be overridden at launch:

    REC2MP4_PYTHON=/some/python  open -a rec2mp4
    REC2MP4_HOME=/some/checkout  open -a rec2mp4

If the interpreter has gone missing the app says so in a Finder dialog rather
than dying silently — the classic failure of a hand-rolled .app.
"""

from __future__ import annotations

import argparse
import os
import plistlib
import shutil
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

BUNDLE_ID = "com.guyshtainer.rec2mp4"
APP_NAME = "rec2mp4"

# The launcher: POSIX sh, no dependencies. $PY/$HOME_DIR are substituted in.
LAUNCHER = """#!/bin/sh
# rec2mp4 launcher — generated by tools/make_macos_app.py, safe to regenerate.
set -u

PY="${{REC2MP4_PYTHON:-{python}}}"
HOME_DIR="${{REC2MP4_HOME:-{home}}}"

if [ ! -x "$PY" ]; then
    PY="$(command -v python3 2>/dev/null || true)"
fi

fail() {{
    /usr/bin/osascript -e "display dialog \\"$1\\" with title \\"rec2mp4\\" \
buttons {{\\"OK\\"}} default button 1 with icon caution" >/dev/null 2>&1
    exit 1
}}

[ -n "$PY" ] && [ -x "$PY" ] || fail "rec2mp4 cannot find a Python to run.\\n\\n\
Expected: {python}\\n\\nSet REC2MP4_PYTHON to a Python that has Pillow and the \
vendored mGBA bindings, then open rec2mp4 again."

[ -d "$HOME_DIR/rec2mp4" ] || fail "rec2mp4 cannot find its code.\\n\\n\
Expected: {home}\\n\\nThe app launches the working copy it was built from. \
Rebuild it with tools/make_macos_app.py, or set REC2MP4_HOME."

cd "$HOME_DIR" || fail "rec2mp4 cannot enter $HOME_DIR"
PYTHONPATH="$HOME_DIR${{PYTHONPATH:+:$PYTHONPATH}}"
export PYTHONPATH
exec "$PY" -m rec2mp4.gui "$@"
"""


def build(dest_dir: Path, python: str, home: Path,
          icon: Path | None = None) -> Path:
    """Write <dest_dir>/rec2mp4.app and return its path."""
    try:
        from rec2mp4 import __version__ as version
    except Exception:                       # a build must not need the package
        version = "0.1.0"

    app = dest_dir / f"{APP_NAME}.app"
    contents = app / "Contents"
    macos, resources = contents / "MacOS", contents / "Resources"
    if app.exists():
        shutil.rmtree(app)
    macos.mkdir(parents=True)
    resources.mkdir(parents=True)

    info = {
        "CFBundleName": APP_NAME,
        "CFBundleDisplayName": APP_NAME,
        "CFBundleIdentifier": BUNDLE_ID,
        "CFBundleExecutable": APP_NAME,
        "CFBundlePackageType": "APPL",
        "CFBundleInfoDictionaryVersion": "6.0",
        "CFBundleShortVersionString": str(version),
        "CFBundleVersion": str(version),
        "LSMinimumSystemVersion": "10.13",
        "LSApplicationCategoryType": "public.app-category.video",
        # Tk draws its own window; without this it renders at 1x on Retina.
        "NSHighResolutionCapable": True,
        # A GUI-only agent would hide the Dock icon — we want the icon.
        "LSUIElement": False,
        "NSHumanReadableCopyright": "GPL-3.0-or-later, (C) 2026 Guy Shtainer",
    }
    if icon is not None and icon.is_file():
        shutil.copy2(icon, resources / icon.name)
        info["CFBundleIconFile"] = icon.stem
    with open(contents / "Info.plist", "wb") as fh:
        plistlib.dump(info, fh)

    launcher = macos / APP_NAME
    launcher.write_text(LAUNCHER.format(python=python, home=str(home)))
    launcher.chmod(0o755)

    # Finder caches bundle icons aggressively; touching the bundle after the
    # icon lands is what makes the new icon show up without a re-login.
    os.utime(app, None)
    if sys.platform == "darwin":
        try:
            subprocess.run(["touch", str(app)], check=False)
        except OSError:
            pass
    return app


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(
        description="Build a double-clickable rec2mp4.app (a launcher for "
                    "this working copy, not a frozen distributable).")
    ap.add_argument("--to", default=str(ROOT / "dist"), metavar="DIR",
                    help="where to write rec2mp4.app (default: dist/)")
    ap.add_argument("--python", default=None, metavar="PATH",
                    help="interpreter the app should launch (default: the "
                         "one running this script, which is why you should "
                         "run it with the rec2mp4 conda env)")
    ap.add_argument("--home", default=str(ROOT), metavar="DIR",
                    help="working copy the app should run (default: this one)")
    args = ap.parse_args(argv)

    if sys.platform != "darwin":
        print("error: .app bundles are macOS-only (see "
              "tools/make_windows_shortcut.ps1 for Windows)", file=sys.stderr)
        return 2

    python = args.python or sys.executable
    icon = ROOT / "assets" / "rec2mp4.icns"
    if not icon.is_file():
        print("note: assets/rec2mp4.icns missing — run "
              "tools/make_icons.py first for a real icon")
        icon = None

    dest = Path(args.to).expanduser()
    dest.mkdir(parents=True, exist_ok=True)
    app = build(dest, python, Path(args.home).expanduser(), icon)

    print(f"built {app}")
    print(f"   launches: {python}")
    print(f"   working copy: {args.home}")
    if "miniconda3/envs/rec2mp4" not in python and "conda" not in python:
        print("   WARNING: that interpreter is probably NOT the rec2mp4 conda "
              "env — the app will open but conversions may fail. Rebuild "
              "with:  <conda-env-python> tools/make_macos_app.py")
    print(f"\nDouble-click it, or drag it to /Applications (it keeps "
          f"pointing at {args.home}).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
